### ISSUE TITLE
Update path for AnalyzeManager in calibtool/resamplers/BaseResampler.py

### ISSUE THREAD

**Issue by YeChen-IDM** [InstituteforDiseaseModeling/dtk-tools#1704]
When running HIV calibration scenario(optim_script.py) with latest dtk-tools code, I met this error:
![image](https://user-images.githubusercontent.com/19782371/51272756-da913080-197f-11e9-9e00-53e6e1e6b04d.png)

This is because AnalyzeManager was moved to simtools.Analysis.AnalyzeManager. We need to update the BaseResampler.py file.

**Comment by braybaud** [comment]
Fixed in #1705, thanks 👍
